---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: ubuntu
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: apache2_php_config-ubuntu-bionic
    image: ubuntu:bionic
    # command: /lib/systemd/systemd
    # privileged: true
  - name: apache2_php_config-ubuntu-focal
    image: ubuntu:focal
    # command: /lib/systemd/systemd
    # privileged: true
provisioner:
  name: ansible
  playbooks:
    create: ../resources/playbooks/create.yml
    destroy: ../resources/playbooks/destroy.yml
    converge: ../resources/playbooks/converge.yml
    prepare: ../resources/playbooks/prepare.yml
  log: true
  options:
    vvv: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
      verbosity: 3
  inventory:
    group_vars:
      all:
        apache2_adminhost_https: false
        apache2_php_config_php_enabled: true
verifier:
  name: testinfra
  directory: ../resources/tests/
